// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsCassy.Tests")>]
[<assembly: AssemblyProductAttribute("FsCassy")>]
[<assembly: AssemblyDescriptionAttribute("Functional F# API for Cassandra")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsCassy.Tests"
    let [<Literal>] AssemblyProduct = "FsCassy"
    let [<Literal>] AssemblyDescription = "Functional F# API for Cassandra"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
